# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#home"
  weight = 10

[[main]]
  name = "People"
  url = "#people"
  weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 40

[[main]]
  name = "Blogs"
  url = "#posts"
  weight = 50
  
[[main]]
  name = "Tags"
  url = "#tags"
  weight = 60